site_name: "Thousand Leaves Notes"
site_url: "https://karine-mue.github.io/thousand_leaves/"
repo_url: "https://github.com/karine-mue/thousand_leaves.git"
theme:
  name: "material"

plugins:
  - search
  - git-revision-date-localized:
      format: "YYYY-MM-DD HH:mm:ss"
      locale: "ja_JP"
      timezone: "Asia/Tokyo"

nav:
  - Home: index.md
  - Linux:
      - Overview: linux/index.md
      - コマンドメモ: linux/cmd.md
      - Shell: linux/shell.md
      - その他: linux/others.md
      - ミニPCを自宅内ファイルサーバにする: linux/samba.md
  - PC構成:
      - Overview: pc-build/index.md
      - ハードウェア: pc-build/hardware.md
      - ソフトウェア: pc-build/software.md
      - その他: pc-build/others.md
  - Python:
      - Overview: python/index.md
      - スクリプト集: python/scripts.md
      - その他: python/others.md
  - R:
      - Overview: R/index.md
      - スクリプト: R/scripts.md
      - その他: R/others.md
  - web:
      - Overview: web/index.md
      - GitHub Pages + MkDocs セットアップ手順: web/setup_github_pages.md
      - その他: web/others.md
  - 統計:
      - Overview: Stats/index.md
      - その他: Stats/others.md
  - VRChat:
      - Overview: vrchat/index.md
      - 視線対策: vrchat/eye_tracking.md
      - モデル調整: vrchat/model.md
      - その他: vrchat/others.md

site_name: "Thousand Leaves Notes"



