site_name: "Thousand Leaves Notes"
theme:
  name: "material"

nav:
  - Home: index.md
  - Linux:
      - Overview: linux/index.md
      - コマンドメモ: linux/cmd.md
      - Shell: linux/shell.md
      - その他: linux/others.md
  - PC構成:
      - Overview: pc-build/index.md
      - ハードウェア: pc-build/hardware.md
      - ソフトウェア: pc-build/software.md
      - その他: pc-build/others.md
  - Python:
      - Overview: python/index.md
      - スクリプト集: python/scripts.md
      - その他: python/others.md
  - R:
      - Overview: R/index.md
      - スクリプト: R/scripts.md
      - その他: R/others.md
  - 統計:
      - Overview: Stats/index.md
      - その他: Stats/others.md
  - VRChat:
      - Overview: vrchat/index.md
      - モデル調整: vrchat/model.md
      - その他: vrchat/others.md

