site_name: "Thousand Leaves Notes"
site_url: "https://karine-mue.github.io/thousand_leaves/"
repo_url: "https://github.com/karine-mue/thousand_leaves.git"
theme:
  name: "material"
  language: "ja"
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.tracking
  favicon: images/favicon.ico
extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-6140GMZ322
  - js/gtag_config.js
  - js/mathjax_config.js # MathJaxの設定を追加
  - js/mermaid_init.js # Mermaidの初期化スクリプト
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      format: "YYYY-MM-DD HH:mm:ss"
      locale: "ja_JP"
      timezone: "Asia/Tokyo"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karine-mue
  generator: false
  version:
    provider: git
    branch: main
    commit: true

nav:
  - Home: index.md
  - Linux:
      - Overview: linux/index.md
      - Shell: linux/shell.md
      - ミニPCを自宅内ファイルサーバにする: linux/samba.md
      - 見つけた対象に対して処理をする(find -exec): linux/find_exec.md
      - キャッシュについて: linux/chache.md
  - PC構成:
      - Overview: pc-build/index.md
      - ハードウェア: pc-build/hardware.md
      - ソフトウェア: pc-build/software.md
      - その他: pc-build/others.md
  - Python:
      - Overview: python/index.md
      - スクリプト集: python/scripts.md
      - その他: python/others.md
  - R:
      - Overview: R/index.md
      - スクリプト: R/scripts.md
      - その他: R/others.md
  - web:
      - Overview: web/index.md
      - MkDocsでTeX数式を表示する方法（MathJax）: web/mathjax.md
      - GitHub Pages + MkDocs セットアップ手順: web/setup_github_pages.md
  - 統計:
      - Overview: Stats/index.md
      - 指標一覧: Stats/metrics.md
      - 分析準備ガイド 兼 チェックリスト: Stats/precheck.md
      - ユースケース別の指標使い分け: Stats/usecase_metrics.md
      - 構造比較アイデア: Stats/comparison-ideas.md
      - その他: Stats/others.md
  - LLM:
      - Overview: LLM/index.md
      - なぜ"嘘"がバレたchatgptは浮気がバレた浮気癖男になるのか: LLM/chatgpt_cheating.md
      - 意味空間における前提破壊の数理モデル化と再現性の探究: LLM/two_layer_SDE_model.md
      - chatgpt彼女ーAI彼女のトリセツー: LLM/chatgpt_kanojo.md
  - VRChat:
      - Overview: vrchat/index.md
      - 視線対策: vrchat/eye_tracking.md
      - モデル調整: vrchat/model.md
      - その他: vrchat/others.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      inline_syntax: ['$', '$']
      block_tag: 'div'
      generic: true
