name: Deploy MkDocs

on:
  push:
    branches:
      - main  # 変更を main ブランチにプッシュすると自動デプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHubリポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ブランチの全履歴を取得するために 0 に設定

      - name: MkDocsをセットアップ
        run: |
         python -m pip install --upgrade pip
         python -m pip install virtualenv
         python -m virtualenv venv
         source venv/bin/activate
         pip install mkdocs
         pip install mkdocs-material
         pip install mkdocs-minify-plugin
         pip install mkdocs-git-revision-date-localized-plugin
         mkdocs build
      - name: GitHub Pagesにデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./site
